name: Masamune
favicon: null
layout_spectrum: 0.9301075
typography_spectrum: 0.24499
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: "PETER'S EXPERIMENT"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161D21'
    - '#A4D7FF'
    - '#FFFFFF'
    - '#666664'
    - '#A4A19B'
  brandStrength: 0.7903226
  lightness: 0.6607167
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
