layout_spectrum: 0.9301075
color:
  saturation: 0.8540989
  lightness: 0.6607167
  brandStrength: 0.4897064
  brandColors:
    - '#161D21'
    - '#A4D7FF'
    - '#FFFFFF'
    - '#666664'
    - '#A4A19B'
  rhythmicContrast: 0.1072494
typography_spectrum: 0.327957
name: Entrepreneur Life
